##### AOSiP #####

# Considering logged in username as maintainer name.
export maintainer="$(whoami) (Generated by device tree.)"

# Write a simple configuration file for AOSiP.
if [[ -d vendor/aosip/products ]]
then
    echo ""
    echo "Considering logged in username as maintainer, please review vendor/aosip/products/aosip_teos.mk once envsetup is done."
    echo "# Simple configuration file for teos" > vendor/aosip/products/aosip_teos.mk
    echo "\$(call inherit-product, device/vestel/teos/aosp_teos.mk)" >> vendor/aosip/products/aosip_teos.mk
    echo "PRODUCT_BUILD_PROP_OVERRIDES := DEVICE_MAINTAINERS=\"${maintainer}\"" >> vendor/aosip/products/aosip_teos.mk
    sed -i 's/aosp\/common.mk/aosip\/config\/common_full_phone.mk/' device/vestel/teos/aosp_teos.mk
    sed -i 's/aosp_teos/aosip_teos/' device/vestel/teos/aosp_teos.mk
    add_lunch_combo aosip_teos-eng
    add_lunch_combo aosip_teos-userdebug
    add_lunch_combo aosip_teos-user
    echo ""
fi
#################


##### AOSP-CAF #####

# Patch vendor/aosp for sane build.
if [[ -f vendor/aosp/common.mk ]]
then
    caftestvar="$(cat vendor/aosp/common.mk | grep ro.aosp-caf.version)"
    if [[ ! -z caftestvar ]]
    then
        echo ""
        echo "You're building AOSP-CAF, need to patch vendor/aosp for proper prop sets and apps..."
        echo ""
        python device/vestel/teos/patch_repo.py
        echo ""
    fi
fi
####################

##### NitrogenOS #####

# Add lunch combo for Nitrogen
if [[ -d vendor/nitrogen ]]
then
    # Do bringup for nitro so we can add lunch combo properly
    echo "" && echo "Bringing up the device tree..." && echo ""
    if [[ ! -z $(which rename) ]]; then
        rename 's/aosp/nitrogen/g' device/vestel/teos/aosp_teos.mk
    else
        echo "You don't have 'rename' installed. Falling back to move..." && echo ""
        pushd device/vestel/teos
        mv {aosp,nitrogen}_teos.mk
        popd
        echo ""
    fi
    sed -i 's/aosp/nitrogen/g' device/vestel/teos/{AndroidProducts,nitrogen_teos}.mk
    sed -i 's/POLICY := 1/POLICY := 0/' device/vestel/teos/BoardConfig.mk
    add_lunch_combo nitrogen_teos-userdebug
fi
######################
